
services:
  web:
    build: .
    image: viache5lav/moneymanagment-web
    command: gunicorn moneyManagment.wsgi:application --bind 0.0.0.0:8000
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/app/staticfiles:ro  # Изменено с static_volume
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

  celery:
    build: .
    image: viache5lav/moneymanagment-celery
    entrypoint: ""
    command: celery -A moneyManagment worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: MoneyManagment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
