# Generated by Django 5.1.4 on 2024-12-30 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybills',
            name='date_to_pay',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 22, 26, 44, 128752)),
        ),
    ]
