# Generated by Django 5.1.4 on 2025-01-10 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_bills', '0009_alter_monthlybills_date_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybills',
            name='date_to_pay',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 13, 4, 47, 564678)),
        ),
    ]
