# Generated by Django 5.1.4 on 2024-12-23 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_or_expence', models.SmallIntegerField()),
                ('target', models.TextField()),
                ('current_balance', models.SmallIntegerField()),
                ('data', models.DateField(default=datetime.datetime(2024, 12, 22, 23, 15, 1, 34391))),
            ],
        ),
    ]
