# Generated by Django 5.1.4 on 2025-01-07 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_wallet_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 20, 54, 37, 77403)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='income_or_expence',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
