# Generated by Django 5.1.4 on 2025-01-10 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_wallet_data_alter_wallet_income_or_expence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 12, 36, 14, 843910)),
        ),
    ]
