# Generated by Django 5.1.4 on 2025-01-10 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_alter_wallet_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 12, 48, 17, 698437)),
        ),
    ]
