# Generated by Django 5.1.4 on 2025-01-11 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_alter_wallet_data_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 22, 1, 40, 754417)),
        ),
    ]
