# Generated by Django 5.1.4 on 2025-01-14 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_alter_wallet_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 22, 58, 39, 36663)),
        ),
    ]
